version: "3.3"

services:
    contibus:
        image: contibus/web
        container_name: contibus
        #        build: .
        env_file: .env
        restart: always
        ports:
            - 8081:8081
